# Generated by Django 4.1.8 on 2023-05-02 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="update",
            new_name="updated",
        ),
    ]
